### ISSUE TITLE
Add Doxygen generation

### ISSUE THREAD

**Issue by bburda** [UmlautSoftwareDevelopmentAccount/AP-Functional-Cluster-Template#6]
This task requires adding the Doxyfile, and the Meson target for generating Doxygen documentation.

**Comment by satletio1** [comment]
i.e. 
`ninja doxygen`

**Comment by bburda** [comment]
Turn on `AUTOBRIEF` https://github.com/UmlautSoftwareDevelopmentAccount/AP-CoreTypes/pull/21#discussion_r436515324

**Comment by satletio1** [comment]
Initial commit of Doxyfile (default configuration).

Also Docker file is in PR in AR-Template repository.
