### ISSUE TITLE
Add missing compiler flags.

### ISSUE THREAD

**Issue by bburda** [UmlautSoftwareDevelopmentAccount/AP-Functional-Cluster-Template#8]
Currently, we use default compiler flags (except for using c++20). 
We must do some analysis, what flags should we use by default in each functional cluster, and add them.

One of them is `-Wall`.  For now, we consider only `GCC 10.0+`

**Comment by slci** [comment]
#17 adds some default warnings via Meson config, please check whether it's needed to be extended.
