### ISSUE TITLE
Add Clang-Tidy to travis and configure AUTOSAR guidelines

### ISSUE THREAD

**Issue by bburda** [UmlautSoftwareDevelopmentAccount/AP-Functional-Cluster-Template#9]

**Comment by slci** [comment]
Since version 0.52.0 Meson automatically add target for clang-tidy (https://mesonbuild.com/Release-notes-for-0-52-0.html#clangtidy-target) To be closed

**Comment by bburda** [comment]
> 
> 
> Since version 0.52.0 Meson automatically add target for clang-tidy (https://mesonbuild.com/Release-notes-for-0-52-0.html#clangtidy-target) To be closed

Yes, this is now more like `add clang-tidy to travis` task with a configuration for Autosar readability checks according to guidelines.

See #16

**Comment by bburda** [comment]
Changed the task name.

**Comment by bburda** [comment]
Update
This task is about the configuration of the clang-tidy for use with Travis CI. 
The clang-tidy should be configured to run before compilation and is should check all project files in directories `include/` and `src/`  (we can skip `tests/`).

The checks should report all warnings as errors.
The checks should be based on https://github.com/UmlautSoftwareDevelopmentAccount/AUTOSAR-Adaptive/blob/master/docs/autosar/adaptive/AUTOSAR_RS_CPP14Guidelines.pdf

for example:
the `typdef` is not allowed according to AUTOSAR guidelines and `using` shall be used instead:
https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-using.html
